# example netlify.toml
[build]
  command = "ng build && ng run sandbox-ng-uni-plugin-demo:serverless:production"
  functions = "netlify/functions"
  publish = "dist/sandbox-ng-uni-plugin-demo/browser"

  [[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200

[[plugins]]
  package = "@netlify/plugin-angular-universal"
