# example netlify.toml
[build]
  command = "ng build && ng run uni-plugin-ui-demo:serverless:production"
  functions = "netlify/functions"
  publish = "dist/uni-plugin-ui-demo/browser"

  [[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200
